src/Entity/DetailCommande.php
<?php

namespace App\Entity;

use App\Repository\DetailCommandeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DetailCommandeRepository::class)]
class DetailCommande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $quantite;

    #[ORM\ManyToOne(targetEntity: Commande::class, inversedBy: 'detailCommande')]
    private $commande;

    #[ORM\ManyToOne(targetEntity: Produit::class, inversedBy: 'detailCommande')]
    private $produit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(?int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->commande;
    }

    public function setCommande(?Commande $commande): self
    {
        $this->commande = $commande;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    //Méthode pour savoir si deux détails sont pareils
    //Comparer le détail en cours avec un détail passé en paramètre
    //Ces détails doivent avoir déjà un id, c'est à dire exister préalablement dans la BD
    public function equals(DetailCommande $detail): bool {
        return $this->getProduit()->getId() == $detail->getProduit()->getId();
    }

    //Obtenir le prix d'un détail
    public function getTotal():float {
        return $this->getProduit()->getPrix() * $this->getQuantite();
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Entity\Commande;
use App\Entity\DetailCommande;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PanierController extends AbstractController
{
    #[Route('/panier/afficher', name: 'basket')]
    public function index(SessionInterface $session, ProduitRepository $repProduit): Response
    {
        $panierCommande = $session->get('panierCommande', new Commande());

        $vars = ['panierCommande' => $panierCommande];
        return $this->render('panier/basket.html.twig', $vars);
    }


    #[Route('/panier/ajouter', name: 'basket-add-product')]
    public function addProduitPlusieurs(Request $req, SessionInterface $session, ProduitRepository $repProduit): Response {

        $id = $req->request->get('id');
        $quantite = $req->request->get('quantite');

        $panierCommande = $session->get('panierCommande', new Commande()); 
        
        $detail = new DetailCommande();
        
        $produit = $repProduit->find($id);
        
        $produit->addDetailCommande($detail);

        $detail->setQuantite($quantite); 
      
        $panierCommande->addDetailCommande($detail);     

        $session->set('panierCommande', $panierCommande);
        return $this->redirectToRoute('basket');
    }


    #[Route('/panier/ajouter/detail/{id}', name: 'basket-add-detail-product')]
    public function panierAddDetail(Request $req, SessionInterface $session, ProduitRepository $repProduit): Response {

        $id = $req->get('id'); // id du produit à rajouter

        $panierCommande = $session->get('panierCommande', new Commande()); // si la variable 'panier' n'existe pas, on initialise l'array

        $detail = new DetailCommande();
        $detail->setProduit($repProduit->find($id));
        $detail->setQuantite(1); // ou plus (reçu en paramètre tel que l'id), si vous mettez un champ pour choisir la quantité dans l'interface

        $panierCommande->addDetailCommande($detail);  // regardez le code de addDetail       

        $session->set('panierCommande', $panierCommande);
        return $this->redirectToRoute('basket');
    }


    #[Route('/panier/effacer/detail/{id}', name: 'basket-remove-detail-product')]
    public function panierRemoveDetail(Request $req, SessionInterface $session, ProduitRepository $repProduit): Response {

        $id = $req->get('id');

        $panierCommande = $session->get('panierCommande', new Commande()); 

        $detail = new DetailCommande();
        $detail->setProduit($repProduit->find($id));
        $detail->setQuantite(1); 

        $panierCommande->removeDetailCommande($detail);      

        $session->set('panierCommande', $panierCommande);
        return $this->redirectToRoute('basket');
    }


    #[Route('/panier/effacer/all/{id}', name: 'basket-delete-product')]
    public function panierEffacerDetail(Request $req, SessionInterface $session) {

        $panierCommande = $session->get("panierCommande");

        $detailsCommandeSession = $panierCommande->getDetailCommande();
        foreach ($panierCommande->getDetailCommande() as $key => $detailSession){
            if ($req->get('id') == $detailSession->getProduit()->getId()){
                $detailsCommandeSession->removeElement($detailSession);
                // plus besoin de chercher, on redirige
                return $this->redirectToRoute('basket');

            }
        }
        return $this->redirectToRoute('basket');
    }


}

templates/panier/basket.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div id="fh5co-about">
		<div class="container">
			<div class="about-content">
				<div class="row animate-box">
                    <h3>Basket</h3>
                
                    <table class="table">
                        <tr>
                            <th>Produit</th>
                            <th>Photo</th>
                            <th>Prix</th>
                            <th>Quantité</th>
                            <th>Total</th>
                            <th>Actions</th>
                        </tr>
                
                            {% for detail in panierCommande.detailCommande %}
                                <tr>
                                    <td>{{ detail.produit.titre }}</td>
                                    <td><img src="{{ asset('./assets/images/' ~ detail.produit.photo) }}" style="width:5rem"></td>
                                    <td class="text-end">{{ detail.produit.prix }} €</td>
                                    <td>{{ detail.quantite }}</td>
                                    <td class="text-end">{{ detail.quantite * detail.produit.prix }} €</td>
                                    <td>
                                        <a href="{{path("basket-add-detail-product", {'id': detail.produit.id})}}" class="btn btn-success">
                                            <i class="bi bi-cart-plus">+</i>
                                        </a>
                                        <a href="{{path("basket-remove-detail-product", {'id': detail.produit.id})}}" class="btn btn-warning">
                                            <i class="bi bi-cart-dash">-</i>
                                        </a>
                                        <a href="{{path("basket-delete-product", {'id': detail.produit.id})}}" class="btn btn-danger">
                                            <i class="bi bi-cart-x">Delete</i>
                                        </a>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="5" class="text-center">Votre panier est vide</td>
                                </tr>
                        
                            {% endfor %}
                    </table>
                    <h4>Total: {{ panierCommande.total }} €</h4>
                    <a href="{{ path ('order') }}"><input class="btn btn-primary btn-outline btn-lg btn btn-success" type="submit" value="Validate"></a>
                   <a href="{{ path ('product') }}"><input class="btn btn-primary btn-outline btn-lg" type="submit" value="Back to shop"></a>
    			</div>
			</div>
		</div>
	</div>
{% endblock %}




















  